CREATE TABLE REDUNICA.TALOGERROR_RU(
FCNOMPROCESO VARCHAR2(50), 
FDFECHAERROR  DATE DEFAULT TRUNC(SYSDATE),
FICODERROR   NUMBER,
FCDESCERROR VARCHAR2(250), 
FISTATUSEJEC NUMBER(1), 
FCUSRMODIFICO VARCHAR2(30) DEFAULT USER NOT NULL, 
FDMODIFICACION DATE DEFAULT SYSDATE NOT NULL 
);