CREATE OR REPLACE TYPE RCACT.TYPTRANCREDET AS OBJECT
(
  FIPAISID NUMBER(5),
  FICANAL NUMBER(5),
  FISUCURSAL NUMBER(10),
  FITRANNO NUMBER(10),
  FICONSDETA NUMBER(10),
  FITIPOREG NUMBER(5),
  FCDATODETA VARCHAR2(255)
)
/
