CREATE OR REPLACE TYPE RCACT.TYPTRANCRECAB AS OBJECT ( 
  FIPAISID     NUMBER(5), 
  FICANAL      NUMBER(5), 
  FISUCURSAL   NUMBER(10), 
  FITRANNO     NUMBER(10), 
  FITRANTIPO   NUMBER(5), 
  FICONSECTIPO NUMBER(10), 
  FDTRANSFECHR DATE, 
  FCTRANWS     VARCHAR2(10), 
  FCTRANUSR    VARCHAR2(10))
/
