CREATE TABLE REDUNICA.TALOGERROR_RU(
FCNOMPROCESO VARCHAR2(50), 
FDFECHAERROR  DATE DEFAULT TRUNC(SYSDATE),
FICODERROR   NUMBER,
FCDESCERROR VARCHAR2(250), 
FISTATUSEJEC NUMBER(1), 
FCUSRMODIFICO VARCHAR2(30) DEFAULT USER NOT NULL, 
FDMODIFICACION DATE DEFAULT SYSDATE NOT NULL 
)
TABLESPACE REDUN_DATA_DAT
;
 
CREATE INDEX REDUNICA.IX_TCCTRLRU1 ON REDUNICA.TALOGERROR_RU 
TRUNC(FDFECHAERROR)
TABLESPACE REDUN_DATA_IDX
NOLOGGING;


GRANT SELECT, INSERT, UPDATE, DELETE ON REDUNICA.TALOGERROR_RU TO REDUNICA;